all :
	gcc philo.c print.c init.c ft_atoi.c m_p.c print_msg.c start.c timestamp.c -pthread -o philo
$(info [number_of_philosophers])
$(info  *          [time_to_die])
$(info  *          [time_to_eat])
$(info  *          [time_to_sleep])
$(info  *          [number_of_times_each_philosopher_must_eat])